# Site settings
title: Sigma Omicron Pi
header-img: fallicc2016.jpg
email: your-email@yourdomain.com
copyright_name: Sigma Omicron Pi
description: "The First Asian-Interest Sorority Est. 1930"
baseurl: "/main"
url: "http://webmistress-sigmaomicronpi.github.io"
instagram_username: national_sopi
github_username:  webmistress-sigmaomicronpi
facebook_username:  sigmaomicronpi
email_username:  webmistress.sopi@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

theme: 
